# Generated by Django 4.2.23 on 2025-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='numero',
            field=models.CharField(max_length=15),
        ),
    ]
