# Generated by Django 4.2.23 on 2025-09-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numero',
            field=models.IntegerField(default=12, max_length=15),
            preserve_default=False,
        ),
    ]
